name: Update README with API Data

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  call-api-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call the API
      id: call_api
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        response=$(curl https://api.awanllm.com/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer $API_KEY" -d '{"model": "Awanllm-Llama-3-8B-Dolfin","messages": [  {"role": "user", "content": "What is the meaning of life?"}]}')
        echo "response=$response" >> $GITHUB_ENV
        content=$(echo $response | jq -r '.choices[0].message.content')
        echo "content=$content" >> $GITHUB_ENV

    - name: Update README
      run: |
        value="${{ env.content }}"
        readme_content=$(cat README.md)
        updated_readme_content=$(echo "$readme_content" | sed "s/<!-- api-value -->/${value}/g")
        echo "$updated_readme_content" > README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with API data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
