name: Update README with API Data

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  call-api-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Changed Files and Call API
      run: |
        # Get changed files
        changed_files=$(git diff --name-only HEAD~1 HEAD)
        echo "Changed files: $changed_files"  # Debugging step

        # Prepare JSON payload
        files_changed=$(echo "$changed_files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        json_payload=$(jq -n \
          --arg repo_owner "${{ github.repository_owner }}" \
          --arg repo "${{ github.event.repository.name }}" \
          --argjson files_changed "$files_changed" \
          '{repo_owner: $repo_owner, repo: $repo, files_changed: $files_changed}')
        echo "JSON Payload: $json_payload"  # Debugging step

        # Call the API
        response=$(curl -s -X POST https://docubot-llpjixmpp-allanwzhangs-projects.vercel.app/document -H "Content-Type: application/json" -d "$json_payload")
        echo "API Response: $response"  # Debugging step
        response_content=$(echo $response | jq -r '.updated_doc')
        echo "$response_content" > response.txt

    - name: Update README
      run: |
        echo "# Documentation" > README.md
        cat response.txt >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with API data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
