name: Update README with API Data

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  call-api-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Changed Files
      id: get_changed_files
      uses: actions/github-script@v6
      with:
        script: |
          const changedFiles = await github.rest.repos.listCommitFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha
          }).then(files => files.data.map(file => file.filename));
          console.log("Changed files: ", changedFiles);  // Print changed files for debugging
          return { changedFiles: JSON.stringify(changedFiles) };


    - name: Call the API
      id: call_api
      run: |
        response=$(curl https://docubot-llpjixmpp-allanwzhangs-projects.vercel.app/document -H "Content-Type: application/json" -d -d '{"repo_owner": "ChangePlusPlusVandy", "repo": "fl-backend", "files_changed": ["controllers/auth-controller.ts"]}')
        response_content=$(echo $response | jq -r '.choices[0].message.content')
        echo "$response_content" > response.txt

    - name: Update README
      run: |
        echo "# Documentation" > README.md
        cat response.txt >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with API data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
