name: Update README with API Data

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  call-api-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Changed Files and Call API
      id: get_changed_files_and_call_api
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const commitSha = context.sha;
          const commit = await github.rest.repos.getCommit({
            owner,
            repo,
            ref: commitSha
          });
          const changedFiles = commit.data.files.map(file => file.filename);
          console.log("Changed files: ", changedFiles);  // Print changed files for debugging

          // Prepare the JSON payload
          const jsonPayload = {
            repo_owner: owner,
            repo: repo,
            files_changed: changedFiles
          };

          const response = await require('axios').post('https://docubot-llpjixmpp-allanwzhangs-projects.vercel.app/document', jsonPayload, {
            headers: {
              'Content-Type': 'application/json'
            }
          });
          const responseContent = response.data.updated_doc;
          console.log("API Response: ", responseContent);  // Debugging step
          return { responseContent: responseContent };

    - name: Update README
      run: |
        echo "# Documentation" > README.md
        echo "${{ steps.get_changed_files_and_call_api.outputs.responseContent }}" >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README with API data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
